parameters:
  vmImage: "macos-10.13"
  platform: "macosx"
  buildSystem: "gmake2"
  installScript: |
    echo "Skipping Install Step"
  buildScript: |
    echo "Nothing to build"
    exit 1
  testScript: |
    echo "No tests, skipping"
  continueOnError: false
  packageDirectory: "sentry-native"

jobs:
  - job: sentry_native_${{ parameters.platform }}
    displayName: Sentry-Native (${{ parameters.platform }})
    continueOnError: ${{ parameters.continueOnError }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      PLATFORM: ${{ parameters.platform }}
      BUILD_SYSTEM: ${{ parameters.buildSystem }}
      PACKAGE_DIR: ${{ parameters.buildSystem }}
      PLATFORM_BUILD_DIR: ${{ parameters.buildSystem }}/gen_${{ parameters.platform }}
    steps:
      - template: prescript-common.yml
      - template: install-premake.yml
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: "current"
          downloadType: "single"
          artifactName: $(ARTIFACT_DIR)
          downloadPath: "."

      - bash: |
          set -eux

          ZIP=./bin/zip.py

          unzip -q ./${ARTIFACT_DIR}/sp-sources.zip
          mv sp-sources "${PACKAGE_DIR}"

          cp -R "${PACKAGE_DIR}/premake" "${PLATFORM_BUILD_DIR}"

          cd "${PLATFORM_BUILD_DIR}"
          premake5 "${BUILD_SYSTEM}" --os="${PLATFORM}"
          cd ../..
          $ZIP "sentry-native-${PLATFORM}.zip" "${PACKAGE_DIR}"
        displayName: "Package generated build files"

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "sentry-native-$(PLATFORM).zip"
          artifactName: $(ARTIFACT_DIR)

      - bash: |
          set -eux

          ${{ parameters.installScript }}
        displayName: "Install Dependencies"

      - bash: |
          set -eux

          cd "${PLATFORM_BUILD_DIR}"

          ${{ parameters.buildScript }}
        displayName: "Run Build Script"

      - bash: |
          set -eux

          cd "${PLATFORM_BUILD_DIR}"

          ${{ parameters.testScript }}
        displayName: "Run Tests"
